// <auto-generated />
using System;
using GoHardAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoHardAPI.Migrations
{
    [DbContext(typeof(TrainingContext))]
    [Migration("20260129023005_AddFriendsAndMessaging")]
    partial class AddFriendsAndMessaging
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Schema changes applied via raw SQL in Program.cs for PostgreSQL compatibility
            // This is a no-op Designer to satisfy EF Core migration tracking
        }
    }
}
