// <auto-generated />
using System;
using GoHardAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GoHardAPI.Migrations
{
    [DbContext(typeof(TrainingContext))]
    [Migration("20260109204500_AddProgramTablesOnly")]
    partial class AddProgramTablesOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");
#pragma warning restore 612, 618
        }
    }
}
