// <auto-generated />
using System;
using GoHardAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoHardAPI.Migrations
{
    [DbContext(typeof(TrainingContext))]
    [Migration("20260202120000_AddMealPlanDataJsonToConversation")]
    partial class AddMealPlanDataJsonToConversation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // This migration adds MealPlanDataJson and WorkoutPlanDataJson columns to ChatConversations
            // The full model is defined in TrainingContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
